### ISSUE TITLE
the external file cannot be joined?

### ISSUE THREAD

**Issue by l1t1** [tableau/hyper-api-samples#104]
I use this python script from https://github.com/tableau/hyper-api-samples/pull/78

query the single file is ok.
```
> select count(*) from external('./t17.csv',COLUMNS => DESCRIPTOR(id int, owner int));
"count"
1499001

> select count(*) from external('./t17_2.csv',COLUMNS => DESCRIPTOR(id int, owner int));
"count"
5001
```
query the two files failed
```
> select a.owner, count(*) from external('./t17.csv',COLUMNS => DESCRIPTOR(id int, owner int)) as a,external('./t17_2.csv',COLUMNS => DESCRIPTOR(id int, owner i
nt)) as b where a.id=b.id group by a.owner ;
Error executing SQL: invalid input syntax for integer: file: './t17_2.csv' line:1 column:1
```

**Comment by wolfroediger** [comment]
You are correct, the header is the problem. The single file queries did not fail because `count(*)` will just count the number of lines in the CSV file. It does not type-check the values for all the columns. So, in your example Hyper does not check that the values for `id` and `owner` are valid integers. Since you did not specify `header` the count should also be off by one. 

The following query will also fail for a single file since now Hyper checks that the values for `owner` are valid integers:

`select owner, count(*) from external('./t17.csv',COLUMNS => DESCRIPTOR(id int, owner int)) group by owner;`

**Comment by l1t1** [comment]
thanks @wolfroediger
