### ISSUE TITLE
Read from InputStream instead of nio.Path?

### ISSUE THREAD

**Issue by tooptoop4** [tableau/hyper-api-samples#23]
Following https://github.com/tableau/hyper-api-samples/tree/main/Tableau-Supported/Java/read-and-print-data-from-existing-hyper-file

Can I read a hyper file from input stream or byte array instead of a Path?

**Comment by vogelsgesang** [comment]
Unfortunately no. Hyper can only open Hyper files from files.

What is your use case for wanting to open them from a stream/byte array?

**Comment by tooptoop4** [comment]
if I have hyper files on s3 or a website url

**Comment by vogelsgesang** [comment]
Ok - that is unfortunately not possible with HyperAPI right now...
So the rest of my questions are with the intent to figure out "How would we have to extend HyperAPI/Tableau Server to better cater for your use case in the future?".

So S3 it is... but what is your use case? Which problem are you trying to solve by using S3? Are you, e.g. using HyperAPI for some kind of custom long-term archival/backup of your extracts? Are you building some custom "incremental refresh" solution? Why are you considering using S3 in the first place?
What is the problem with just downloading the files from S3 and storing them to disk before opening them with HyperAPI? Is it file size? Download speeds/volumes? Limited local disk size, e.g. because you are running in AWS Lambda?
Do you need read-write access to the Hyper files or is read-only enough?

In general, Hyper has two requirements for its file storage:
* it needs read-write access. Otherwise, commands like `UPDATE` or `INSERT` would be impossible to execute
* it needs access to arbitrary locations within the files. I.e. it might need to read data from the end of the file, the middle of the file or somewhere else. In particular, the file format is not designed as a streaming format.

In case, read-only access is sufficient for your scenario, the first point is a no-brainer...
The 2nd point, i.e. random-access within files, would be achievable with S3 (which can read files partially and skip over other files). It would require quite some engineering work from our side, though...

**Comment by tooptoop4** [comment]
I am after read-only access. The problem is 'limited local disk size'

**Comment by jkammerer** [comment]
We now have the ability to access S3 directly. See: 
https://help.tableau.com/current/api/hyper_api/en-us/reference/sql/functions-srf.html#FUNCTIONS-SRF-EXTERNAL
